apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-data-mongodb-tolerations-0
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: manual
