apiVersion: v1
kind: Service
metadata:
  name: mongodb-nodeport
spec:
  type: NodePort
  selector:
    app: mongodb
  ports:
    - name: mongodb
      port: 27017
      targetPort: 27017
      nodePort: 30000 # choose any available port number between 30000 and 32767
